### ISSUE TITLE
Exclude router things

### ISSUE THREAD

**Issue by Guria** [garth/cerebral-modules#3]
I am pretty sure that `cerebral-react-modules` shouldn't setup router stuff at all.

First of all with `cerebral` app doesn't have to deal with routing at all. Let keep things simple here.
Module author should deal only with components and signal/actions stuff.

Second point is app author would have better idea how app routes should be set up.
It also could involve custom authorization actions which is app specific.

So my point is: signals to make some module component active should be implemented by app author. As well as binding it to routes.

**Comment by Guria** [comment]
If module needs some setup after it routed it should use `componentDidMount` lifecycle callback to trigger signal call.

**Comment by garth** [comment]
component did mount will be called each time the module is loaded into the view, which can be used, but init will be called one time, which can also be used by services that don't have a component.

**Comment by garth** [comment]
@Guria So if we don't register routes, perhaps we should export signal chains that can be used by the app to add to routing?

**Comment by Guria** [comment]
Yes. I think we can just return necessary info from `loadModules` call

**Comment by Guria** [comment]
>  but init will be called one time, which can also be used by services that don't have a component.

init signal could be called directly inside `init` function call. Just like I did in `cerebral-hoodie`
https://github.com/cerebral/cerebral-hoodie/blob/master/index.js#L27

**Comment by garth** [comment]
the module:

``` js
import routed from './chains/routed';
function init(controller) {
  return {
    routed
  }
}
```

the module loader:

``` js
return modules.reduce((chains, item) => {
  chains[item.name] = item.init(controller);
  return chains;
}, {});
```

**Comment by garth** [comment]
ok, I like the idea of using signals for init. But if we have lots of modules there are a lot of signals running on app start.

What if each module exports an init chain which are collected an executed in a single app init signal?

**Comment by Guria** [comment]
@garth seems great idea.
go check out #4

**Comment by garth** [comment]
Done
