### ISSUE TITLE
unbound from react

### ISSUE THREAD

**Issue by Guria** [garth/cerebral-modules#4]
Seems we can free it from `react`. Component could be whatever or doesn't exist at all.
For example, `cerebral-hoodie` or even `cerebral-router` could be rewrited to be loaded with `cerebral-modules`
We can still provide `render` + `moduleSwitch` for view layers within this or as separate packages.

**Comment by garth** [comment]
@Guria The only reason why I made it react is because of the ModuleSwitch component. But we could make it separate as you suggest.

**Comment by Guria** [comment]
I think it could be safely moved to `cerebral-react`

**Comment by garth** [comment]
Ok, I'll move this repo to cerebral-modules.

**Comment by Guria** [comment]
@garth 
Do not hurry much. I'll suggest also a way to redefine default state path for switcher as well as message before pulling it to `cerebral-react`

**Comment by Guria** [comment]
> Ok, I'll move this repo to cerebral-modules.

~~I see an https://github.com/garth/cerebral-react in repo path right now :D~~

Hehe

**Comment by garth** [comment]
OK, so I've removed the router and react component, so the react component will now need to be moved into cerebral-react or a new cerebral-modules-react lib.
