### ISSUE TITLE
next step

### ISSUE THREAD

**Issue by Guria** [garth/cerebral-modules#6]
Now cerebral inspired by our `cerebral-modules` project has included `controller.extends(modules)` experimental support. It accepts hash of modules: 

``` js
{
  moduleName: {
    init (controller, name) {
      var meta;
      /* module initialization */
      return meta;
    },
    signalA: []
  }
}
```

I think it would be enough for most distributable modules like `cerebral-pouchdb`.
Since that `cerebral-modules` would be not about distribution but about app level modules organisation.
It would be pluggable itself and will provide some set of default plugins which will enable extra power for your app modules.

For example, as app author you can decide to use `initial chains` and `define routes` plugins.
So when your app level module init method returns 

```
{
  init: [action],
  router: routerConfig
}
```

`cerebral-modules` and it's plugins would take care on init signal and routing

**Comment by garth** [comment]
@Guria Looks like a lot of module stuff has been merged into cerebral core and cerebral-react.

Do you think that there is still value to add by making cerebral-modules do some higher level work as you suggest?

**Comment by Guria** [comment]
Yeap. I think it still worth it. Will explore it a little bit later

**Comment by Guria** [comment]
Okay. Latest `cerebral@0.29` modules API are pretty cool. There is definetly no need in this project anymore. :tada:
